//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityUrunProje
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Kullanici
    {
        public byte AdminId { get; set; }
        public string AdminKullanici { get; set; }
        public string AdminSifre { get; set; }
    }
}
